export default {
  LOAD_COUNTERS: 'LOAD_COUNTERS',
  CREATE_COUNTER: 'CREATE_COUNTER',
  INCREMENT_COUNTER: 'INCREMENT_COUNTER',
  DECREMENT_COUNTER: 'DECREMENT_COUNTER',
  REMOVE_COUNTER: 'REMOVE_COUNTER'
};
